### ISSUE TITLE
Soucis pour construction sur DEBIAN SID

### ISSUE THREAD

**Issue by CyrilleBiot** [mothsART/gSpeech#4]
Hello
Bon j'essaye de jouer avec gSpeech. J'avoue que je développe sous debian SID (mon PC) et non primtux. Je porte ensuite les paquets vers primtux. Plus simple pour moi. Et pas fan d'ubuntu.
J'ai un soucis d'install de gspeech

```
python3 source/encoder-mots.py 
/home/ragnarok/git/encoder_mots/source/encoder-mots.py:19: PyGIWarning: Gst was imported without specifying a version first. Use gi.require_version('Gst', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, GdkPixbuf, Gdk, Gst
Traceback (most recent call last):
  File "/home/ragnarok/git/encoder_mots/source/encoder-mots.py", line 23, in <module>
    from speech.conf import Conf
ModuleNotFoundError: No module named 'speech'
```

Du coup j'ai cloné et me disant que j'allais construire le paquet manquant

```
⌚16:24:08 ▶ ragnarok@valhalla ▷ ~/git/gSpeech
$ make build.debian
debuild #binary package : .deb, alias of dpkg-buildpackage -rfakeroot -d -us -uc
 dpkg-buildpackage -us -uc -ui
dpkg-buildpackage: info: paquet source gspeech
dpkg-buildpackage: info: version source 0.11.0
dpkg-buildpackage: info: distribution source xenial
dpkg-buildpackage: info: source changé par Jérémie Ferry <jerem.ferry@gmail.com>
 dpkg-source --before-build .
dpkg-buildpackage: info: architecture hôte amd64
 fakeroot debian/rules clean
dh clean --with python3
dh: warning: Compatibility levels before 10 are deprecated (level 9 in use)
dh: error: unable to load addon python3: Can't locate Debian/Debhelper/Sequence/python3.pm in @INC (you may need to install the Debian::Debhelper::Sequence::python3 module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.32.1 /usr/local/share/perl/5.32.1 /usr/lib/x86_64-linux-gnu/perl5/5.32 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.32 /usr/share/perl/5.32 /usr/local/lib/site_perl) at (eval 10) line 1.
BEGIN failed--compilation aborted at (eval 10) line 1.

make: *** [debian/rules:3 : clean] Erreur 25
dpkg-buildpackage: erreur: fakeroot debian/rules clean subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed
make: *** [makefile:35 : build.debian] Erreur 29
```

Bon dans les choux et en plus je ne saisis pas ce qui foire.

Est ce que ça te parle ?

Merci ;)

**Comment by mothsART** [comment]
Bon, je te réponds un peu en speed.
Le soucis provient d'une dépendance de build non satisfaite (donc à priori, rien à voir avec le fait que j'utilise Ubuntu et toi Debian Sid) : il manquait "dh-python" qui ne doit sans doute pas être présent sur ton poste alors que moi je l'avais avant même de créer le paquet donc je suis passé complètement à côté.
Si tu veux voir le correctif : https://github.com/mothsART/gSpeech/commit/7b0f71017a4ec7228d2d5b951e9675f20178cd77
(j'ai corrigé le warning aussi dans la foulée en passant la version de compat de 9 à 10)
Tu peux retenter un "git pull" puis "make build.debian" et ça devrait rentrer dans l'ordre.

Si ça n'est pas le cas et que ça deviens spécifique Debian Sid, je tenterais de corriger via docker.

**Comment by CyrilleBiot** [comment]
Nickel
le paquet est créé
```
ls gspeech_0.11.0*
gspeech_0.11.0_all.deb  gspeech_0.11.0_amd64.build  gspeech_0.11.0_amd64.buildinfo  gspeech_0.11.0_amd64.changes  gspeech_0.11.0.dsc  gspeech_0.11.0.tar.gz
```


Just une petite erreur gpg mais je ne pense pas que ce soit fort impactant

```
Now signing changes and any dsc files...
 signfile dsc gspeech_0.11.0.dsc Jérémie Ferry <jerem.ferry@gmail.com>
gpg: « Jérémie Ferry <jerem.ferry@gmail.com> » a été ignorée : No secret key
gpg: /tmp/debsign.wK9YCFwu/gspeech_0.11.0.dsc: clear-sign failed: No secret key
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1112:
running debsign failed
make: *** [makefile:35 : build.debian] Erreur 29
```

Bon je l'installe asap et vois si ça passe ;)

Thx

**Comment by CyrilleBiot** [comment]
Pour info, voici les dépendances qu'ils manquaient 
`    python3-dev python3-setuptools dh-python`

**Comment by mothsART** [comment]
Exact mais "python3-dev" "python3-setuptools" était dans les build-depends donc le message devait être un peu moins scabreux.
Merci de ton ticket, j'aurais sans doute jamais identifié cette coquille.

**Comment by CyrilleBiot** [comment]
ALors pour info le paquet crée pose soucis car il n'embarque par les dépendances 

 gspeech dépend de python3-gst-1.0 ; cependant :
  Le paquet python3-gst-1.0 n'est pas installé.
 gspeech dépend de libttspico-utils ; cependant :
  Le paquet libttspico-utils n'est pas installé.
 gspeech dépend de sox ; cependant :
  Le paquet sox n'est pas installé.

Installé à la main, ça passe.

Mais ça plante lors de l'application quand on clique sur Ecouter mp3 ou clic droit sur les lettres

```
Error: gst-resource-error-quark: Ressource introuvable. (3) ../plugins/elements/gstfilesrc.c(536): gst_file_src_start (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin3/GstFileSrc:source:
No such file "/home/ragnarok/.cache/gSpeech/speech.wav"
Error: gst-resource-error-quark: Ressource introuvable. (3) ../plugins/elements/gstfilesrc.c(536): gst_file_src_start (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin4/GstFileSrc:source:
No such file "/home/ragnarok/.cache/gSpeech/speech.wav"
Error: gst-resource-error-quark: Ressource introuvable. (3) ../plugins/elements/gstfilesrc.c(536): gst_file_src_start (): /GstPlayBin:player/GstURIDecodeBin:uridecodebin5/GstFileSrc:source:
No such file "/home/ragnarok/.cache/gSpeech/speech.wav"
```
;)

**Comment by mothsART** [comment]
Le fichier control est tout à fait à jour la dessus : https://github.com/mothsART/gSpeech/blob/master/debian/control
Ca me parait assez étonnant ton histoire...(va falloir quand même que je test un peu avec un docker)
Pour ton histoire de .cache, le correctif de @upskaling va peut-être te débloquer mais sans, je n'arrive pas à reproduire sur une ubuntu et sur nix (je supprime le répertoire gSpeech et il est recréé en auto)
J'enquète dessus avant de proposer un patch   dégeu.

**Comment by mothsART** [comment]
Ah, je comprend mieux ton soucis.
C'est quand tu pilotes gSpeech via ton soft que ça plante... encore un défaut non anticipé lié à l'utilisation de gSpeech en tant que bibliothèque. Je fais un correctif mais en attendant, en créant le dossier home/ragnarok/.cache/gSpeech, ça devrait fonctionner.

**Comment by mothsART** [comment]
Bon, c'est corrigé : https://github.com/mothsART/gSpeech/pull/6 (plus qu'à pull)

**Comment by CyrilleBiot** [comment]
OK ça passe nickel.
merci ;)
