### ISSUE TITLE
problème pour installation sur pop os 22.04

### ISSUE THREAD

**Issue by ben3291** [mothsART/gSpeech#8]
bonjour 
le ppa ne fonctione plus 

et je n'arrive pas a installer gspeech avec le fichier tar.jz

merci de votre aide

**Comment by mothsART** [comment]
ok, je vais voir déjà pour que le ppa supporte la 22.04

**Comment by mothsART** [comment]
voilà. Ça met un peu de temps avant d'être disponible : ça devrait être disponible demain.

**Comment by ben3291** [comment]
merci je vais faire un retour sur votre travail dans  le podcast que j'anime sur le monde du libre

**Comment by mothsART** [comment]
ok, n'hésitez pas à mettre le lien
